name: Albilad Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dowload the Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
      
      - name: Install Gatsby
        run: npm install gatsby-cli@latest

      - name: Build Gatsby
        run: gatsby build

  Functional-Test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Functional Stage"
      - run: sleep 30


  Security-Test:
    runs-on: ubuntu-latest
    needs: Functional-Test
    steps:
      - run: echo "Security Stage"
      - run: sleep 30

  Deploy:
    runs-on: ubuntu-latest
    needs: Security-Test
    steps:
      - run: echo "Deploy Stage"
      - run: sleep 30

