name: Albilad Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build Stage"
      - run: sleep 30

  Functional-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Functional Stage"
      - run: sleep 30


  Security-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Security Stage"
      - run: sleep 30

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy Stage"
      - run: sleep 30

